### ISSUE TITLE
Compatability Patch for Making History/Restrock+

### ISSUE THREAD

**Issue by Linard11** [post-kerbin-mining-corporation/NearFutureLaunchVehicles#102]
Would it be possible to include a Patch for Making History/Restock+

Restock+ already has a compatibility patch for MakingHistory, but NF Launch Vehicles does not, leading to duplicate parts (e.g. the 5m fuel tanks)

**Comment by ChrisAdderley** [comment]
This already exists and seems to be working fine in my install. 

There is a current bug in it where it will not hide the MH tanks is Restock is not installed though.
