### ISSUE TITLE
NearFutureLaunchVehicles Tanks gain weight, when NearFutureConstruction is added

### ISSUE THREAD

**Issue by mjungnickel18** [post-kerbin-mining-corporation/NearFutureLaunchVehicles#111]
Hi,

I have the weird "bug", that if I add NearFutureConstruction to my 1.10.1 KSP Game including NearFutureLaunchVehicles, the 5 and 7.5m tanks are gaining weight. 

For example the NR-6400 Fuel tank increases from 36 to 40 tons, the NR-51200 goes from 288 to 320 tons.

![image](https://user-images.githubusercontent.com/41702029/91618802-b125ec80-e98b-11ea-95ce-1aa210bea2f9.png)

**Comment by LouisB3** [comment]
FYI - I was unable to reproduce on KSP 1.10.1 with both Near Future Construction and Launch Vehicles installed. 

![Screenshot 2020-12-20 00 14 00](https://user-images.githubusercontent.com/9939641/102705706-70aeef00-4258-11eb-937c-139bd5d3c403.png)

**Comment by ChrisAdderley** [comment]
Neither was I.
