### ISSUE TITLE
[Balance] Low thruster power on aerodynamic RCS

### ISSUE THREAD

**Issue by LouisB3** [post-kerbin-mining-corporation/NearFutureLaunchVehicles#115]
The heavy aerodynamic RCS blocks are quite large but only have a thrusterPower of 4, which seems pretty weak for maneuvering 5m/7.5m vessels in atmosphere. For comparison, the stock Vernor engine has a thrusterPower of 12, and the multi-port version of it in KRE is pretty effective for maneuvering ~3.75m boosters in atmo.

I suggest increasing thrusterPower for these RCS blocks to 12.

**Comment by ChrisAdderley** [comment]
Is this a 'seems' based on the numbers, or backup up by gameplay? I felt generally that 4 was sufficient in early tests.

**Comment by LouisB3** [comment]
I've tried to use these RCS (with 4x symmetry) on 7.5m boosters, with little effect. I could certainly do more testing to confirm. 

I should probably clarify whether I've been using these consistently with their intended use case. I've been trying to use these to turn around a freshly detached lower stage so that I can do a boostback burn to KSC from the mid- to upper-atmosphere... is this an appropriate expectation?

**Comment by ChrisAdderley** [comment]
Increase in last release.
