### ISSUE TITLE
Error in FX Definition for fx_gasBurst_white

### ISSUE THREAD

**Issue by JustaSimpleUser** [post-kerbin-mining-corporation/NearFutureLaunchVehicles#121]
Missing commas after the second parameter of the fx_gasBurst_white property in three parts' config files (nflv-separator-75-1, nflv-cargo-tube-5-1 and cargo-tube-75-1) cause MM errors "PartLoader ERROR: bad effect node definition at fx_gasBurst_white".  In order:

1. line 23 - "fx_gasBurst_white = 0.0, 0.231 0.0, 0.0, 1.0, 0.0, decouple" should be "fx_gasBurst_white = 0.0, 0.231, 0.0, 0.0, 1.0, 0.0, decouple"
2. line 64 - "fx_gasBurst_white = 0.0, 0.2 0.0, 0.0, 1.0, 0.0, decouple" should be "fx_gasBurst_white = 0.0, 0.2, 0.0, 0.0, 1.0, 0.0, decouple"
3. line 64 - "fx_gasBurst_white = 0.0, 0.2 0.0, 0.0, 1.0, 0.0, decouple" should be "fx_gasBurst_white = 0.0, 0.2, 0.0, 0.0, 1.0, 0.0, decouple"

I would love to make a pull request but I have no experience creating one (how do a make a minor change like this) and don't know which branch I should use (dev?).

**Comment by ChrisAdderley** [comment]
Thanks, I made the change.

**Comment by ChrisAdderley** [comment]
Released
