### ISSUE TITLE
Payload fairings' "Black and White" variant appears untextured

### ISSUE THREAD

**Issue by Wyzard256** [post-kerbin-mining-corporation/NearFutureLaunchVehicles#127]
For both the 5m and 7.5m fairings, selecting the "Black and White" variant makes the fairing appear untextured gray.  The texture name in the config file is "restock-fairing-5-1-blackwhite", but the DDS file is actually named "restock-fairing-25-1-blackwhite".

**Comment by ChrisAdderley** [comment]
Sorted out in last release
