### ISSUE TITLE
engine-lfo-25-1 missing

### ISSUE THREAD

**Issue by bob82fr** [post-kerbin-mining-corporation/NearFutureLaunchVehicles#128]
Hi,

Found an issue with the engine-lfo-25-1 file missing. So I was not able to load vessels from workshop. Corrected its by changing in the engine-lfo-advanced-25-1-deprecated.cfg file ligne 10 :
model = NearFutureLaunchVehicles/Parts/Engine/engine-lfo-advanced/engine-lfo-advanced-25-1
by
model = NearFutureLaunchVehicles/Legacy/Engine/engine-lfo-advanced/engine-lfo-advanced-25-1

I hope it s the good operation to do, if it is, I hope it ll add to the next version too. Seems to wrok on my steam installation with CKAN, lasts versions.

**Comment by ChrisAdderley** [comment]
This part was removed over a year ago and should not be used. All of the parts under Legacy are under threat of permanent removal probably within the next month or two. I recommend you remove them from your ships and replace them with the newer versions.

**Comment by bob82fr** [comment]
ok, Thanks.
