### ISSUE TITLE
Proposal: Include Stock textures of fairings for the 5m and 7m fairing

### ISSUE THREAD

**Issue by KSP-Rocketeer** [post-kerbin-mining-corporation/NearFutureLaunchVehicles#130]
Proposal: including of the shiny silver/metallic fairing texture of the stock fairing variants to the NF-Launch vehicles fairings in 5m and 7m, so that they fit to the stock fairing series.

**Comment by ChrisAdderley** [comment]
This was added to the 5m fairings in the last release. It won't however be added to the 7.5m fairings as I would need to create additional versions of the base, and the reflective shaders honestly really really suck :(.

**Comment by KSP-Rocketeer** [comment]
Ah... so that's no easy copy/paste from the stock shaders? That's sad, but okay. 
Thanks for your efforts.
