### ISSUE TITLE
nflv-cluster-mount-lower-5-4 has one incorrect attach node

### ISSUE THREAD

**Issue by danfarnsy** [post-kerbin-mining-corporation/NearFutureLaunchVehicles#133]
The outermost ring of attach nodes for nflv-cluster-mount-lower-5-4 has one node misplaced, overlapping with the inner ring of attach nodes. With 18 engines attached, one slot is empty and two engines occupy the same space.

**Comment by ChrisAdderley** [comment]
![image](https://github.com/user-attachments/assets/c831eeb7-bbb9-4c80-9064-dc81cc975e77)
I don't see this issue occurring.
