### ISSUE TITLE
5m fairing is whole grey

### ISSUE THREAD

**Issue by owl7777** [post-kerbin-mining-corporation/NearFutureLaunchVehicles#134]
5m fairing, as the description says comes in serval colour options. The base of the fairing is colored, but the shell itself is not. It is whole grey, none of the colors work.
![image](https://user-images.githubusercontent.com/86301422/147359176-1dad6abd-9f4f-4cef-be8c-b5d27500cbc8.png)
This is the image of this weird phenomenon

**Comment by owl7777** [comment]
KSP 1.12.3, i forgot to add it

**Comment by ChrisAdderley** [comment]
Can't reproduce the issue. 
![image](https://github.com/user-attachments/assets/c4e94546-8cb7-40f9-b48a-7aab0b666b82)
