### ISSUE TITLE
Cluster mounts

### ISSUE THREAD

**Issue by Lathari** [post-kerbin-mining-corporation/NearFutureLaunchVehicles#140]
Sometimes engines aren't in their correct positions after attachment, creating torque. Selecting engine in offset mode and resetting it with space resolves this, but sometimes you don't notice and vessel suddenly steers itself. 

Engines just placed:
![no_reset](https://user-images.githubusercontent.com/2624753/194322500-6ab24754-0f2e-4bf7-ae06-f90815305be3.png)

After resetting offset:
![after_reset](https://user-images.githubusercontent.com/2624753/194322855-1d641dcb-bade-4fa5-be87-0f349992753a.png)

**Comment by ChrisAdderley** [comment]
This seems like a limitation of stock.
