### ISSUE TITLE
Since the stock 5m fuel tanks get substituted by these N fuel tanks, is there a way to cancel that?

### ISSUE THREAD

**Issue by mysynka** [post-kerbin-mining-corporation/NearFutureLaunchVehicles#141]
I like doing stock replicas of real rockets, and sometimes I need to use 5m fuel tanks. With the Janitor’s Closet mod, I can filter out the various mods I have downloaded, included this one, so it only shows stock parts. However, this mod changes the stock 5m fuel tanks by its own fuel tanks. I was wondering if there is a way to cancel that so I still have the normal fuel tanks. I don’t want to uninstall the mod since the cargo bays are, in my opinion, awesome, as well as the 7.5m parts allowing me to make bigger bom- I mean, rockets.

**Comment by ChrisAdderley** [comment]
Just delete this file! It will make it so you have all the sets of tanks in your install. 
https://github.com/post-kerbin-mining-corporation/NearFutureLaunchVehicles/blob/master/GameData/NearFutureLaunchVehicles/Patches/NFLaunchVehiclesOverlappingParts.cfg
