### ISSUE TITLE
NFLV/tweakscale incompatibility, possibly due to being an outdated mod

### ISSUE THREAD

**Issue by koi-la-end** [post-kerbin-mining-corporation/NearFutureLaunchVehicles#142]
narrowed down a performance hit i was getting in VAB and flight when using any parts from this pack with tweakscale companion. seems to me that other PKMC packs have something that this one doesn't that makes them more compatible. anyone have any ideas what that is so i can just dig in and patch it manually?

**Comment by ChrisAdderley** [comment]
Tweakscale issues -> tweakscale repo
