### ISSUE TITLE
5m fairing looks weird (stale will reopen issue with log included

### ISSUE THREAD

**Issue by mrdiamondmanguydudeman** [post-kerbin-mining-corporation/NearFutureLaunchVehicles#145]
![20240817172637_1](https://github.com/user-attachments/assets/e5365acb-e4ec-4218-ad22-af0f5b8017da)
the 5m fairing looks weird, this happened after I uninstalled restock, is there anything with restock or near future launch vehicles that does this? is this a restock problem?

**Comment by mrdiamondmanguydudeman** [comment]
also 1.12.5

**Comment by ChrisAdderley** [comment]
You would need to add a log for me to look more into this.

However it's possible you did not completely remove restock and the patch that uses code from restock to fix the fairing materials is still triggering.

**Comment by mrdiamondmanguydudeman** [comment]
I'll add a log

**Comment by mrdiamondmanguydudeman** [comment]
I couldnt use pastebin to add a log because it is 7 mb and pastebins maximum is 512 kb

**Comment by mrdiamondmanguydudeman** [comment]
any other way?

**Comment by ChrisAdderley** [comment]
The internet provides many avenues of uploading files, I don't know what's best for you.

**Comment by mrdiamondmanguydudeman** [comment]
https://paste.drhack.net/?9222bf1a8718421d#6eUDMnrSjbuSxVSPmVbzWZZENWrnPcktSjdBy62yfb3o
i found an alternative

**Comment by mrdiamondmanguydudeman** [comment]
okay i think this issue is dead
