### ISSUE TITLE
Feature request: Launch clamps

### ISSUE THREAD

**Issue by Vladimir-csp** [post-kerbin-mining-corporation/NearFutureLaunchVehicles#55]
Big cool launch vehicles need big cool launch clamps.
How about Soyuz-style counterweighted arms?
Extra challenge: actually script them to autorelease when the rocket starts moving up.

**Comment by ChrisAdderley** [comment]
I don't think I have any desire for more extra challenge these days :O

**Comment by ChrisAdderley** [comment]
Closing this because well, finally decided to never do it ;)
